/*
 *  File: product.js
 *  Type: DataFixture
 *  Generated by: Mongoose-Fixture (v0.4.1)
 *
 */

// @callback must be returned
// expects (err, object)
// object can be an array of data-documents, or a kwarg['dataFixtures']
// mongoose is the instance of mongoose being used (has schemas)
// conn is the current native mongodb connection (will contain models)
module.exports = function(mongoose, conn, callback) {

    // standard callback error
    var error = null;

    // create your data documents using object-literals
    var fixture = [];

    /*
     * Example of adding a data document/fixture item
     */
    fixture.push({
        // by not defining an _id mongoose-fixture
        // will by default set a mongo ObjectID
        // defining one manually will override mongoDB
        name: "Play for Java: Covers Play 2",
        type: "Book",
        description: "Play for Java shows you how to build Java-based web applications using the Play 2 framework. The book starts by introducing Play through a comprehensive overview example. Then, you'll look at each facet of a typical Play application, both by exploring simple code snippets and by adding to a larger running example. Along the way, you'll contrast Play and JEE patterns and learn how a stateless web application can fit seamlessly in an enterprise environment.",
        company: "Manning Publications",
        price: 30,
        imagePath: "public/images/play-for-java.png",
        rating: 4.5,
        category: "Computer",
        author: "Nicolas Leroux",
        publicationDate: "2014-03-31",
        numPage: 320
    });

    fixture.push({
        name: "MongoDB: The Definitive Guide",
        type: "Book",
        description: "Manage the huMONGOus amount of data collected through your web application with MongoDB. This authoritative introduction—written by a core contributor to the project—shows you the many advantages of using document-oriented databases, and demonstrates how this reliable, high-performance system allows for almost infinite horizontal scalability.",
        company: "O'Reilly Media",
        price: 24,
        imagePath: "public/images/mongodb.png",
        rating: 4.5,
        category: "Computer",
        author: "Kristina Chodorow",
        publicationDate: "2013-06-21",
        numPage: 432
    });

    fixture.push({
        name: "JavaScript & jQuery: The Missing Manual",
        type: "Book",
        description: "JavaScript lets you supercharge your HTML with animation, interactivity, and visual effects—but many web designers find the language hard to learn. This jargon-free guide covers JavaScript basics and shows you how to save time and effort with the jQuery library of prewritten JavaScript code. You’ll soon be building web pages that feel and act like desktop programs, without having to do much programming.",
        company: "O'Reilly Media",
        price: 16.91,
        imagePath: "public/images/javascript-jQuery-the-missing-manual.png",
        rating: 4.5,
        category: "Computer",
        author: "David Sawyer McFarland",
        publicationDate: "2011-10-31",
        numPage: 538
    });

    fixture.push({
        name: "Secrets of the JavaScript Ninja",
        type: "Book",
        description: "Secrets of the Javascript Ninja takes you on a journey towards mastering modern JavaScript development in three phases: design, construction, and maintenance. Written for JavaScript developers with intermediate-level skills, this book will give you the knowledge you need to create a cross-browser JavaScript library from the ground up.",
        company: "Manning Publications",
        price: 17.49,
        imagePath: "public/images/secrets-of-the-javascript-ninja.png",
        rating: 4.5,
        category: "Computer",
        author: "David Sawyer McFarland",
        publicationDate: "2013-12-28",
        numPage: 392
    });

    fixture.push({
        name: "The 7 Habits of Highly Effective People",
        type: "Book",
        company: "Simon & Schuste",
        description: "One of the most inspiring and impactful books ever written, The 7 Habits of Highly Effective People has captivated readers for 25 years. It has transformed the lives of Presidents and CEOs, educators and parents— in short, millions of people of all ages and occupations.",
        price: 16.21,
        imagePath: "public/images/the-7-habits.png",
        rating: 4.5,
        category: "Self improvement",
        author: "Stephen R. Covey",
        publicationDate: "2013-11-19",
        numPage: 432
    });

    fixture.push({
        name: "Tony Northrup's DSLR Book: How to Create Stunning Digital Photography",
        type: "Book",
        company: "Mason Press",
        description: "Stunning Digital Photography is much more than a book; it's a hands-on, self-paced photography class with over 9 hours of online training videos and free help from the author and other readers. That's why award-winning author and photographer Tony Northrup's book is the the first photography e-book with over 100,000 readers.",
        price: 12.98,
        imagePath: "public/images/tony-northrup-dslr-book-how-to-create-stunning-digital-photography.png",
        rating: 4.5,
        category: "Photography",
        author: "Tony Northrup",
        publicationDate: "2012-11-1",
        numPage: 432
    });

    fixture.push({
        name: "Eat That Frog!: 21 Great Ways to Stop Procrastinating and Get More Done in Less Time",
        type: "Book",
        description: "The legendary Eat That Frog! (more than 450,000 copies sold and translated into 23 languages) provides the 21 most effective methods for conquering procrastination and accomplishing more. This new edition is revised and updated throughout, and includes brand new information.",
        company: "Berrett-Koehler Publishers",
        price: 8.09,
        imagePath: "public/images/eat-that-frog.png",
        rating: 4.5,
        category: "Self improvement",
        author: "Brian Tracy",
        publicationDate: "2007-01-01",
        numPage: 128
    });

    fixture.push({
        name: "Steve Jobs",
        type: "Book",
        description: "Based on more than forty interviews with Jobs conducted over two years—as well as interviews with more than a hundred family members, friends, adversaries, competitors, and colleagues—Walter Isaacson has written a riveting story of the roller-coaster life and searingly intense personality of a creative entrepreneur whose passion for perfection and ferocious drive revolutionized six industries: personal computers, animated movies, music, phones, tablet computing, and digital publishing.",
        company: "Simon & Schuster",
        price: 14.44,
        imagePath: "public/images/steve-jobs.png",
        rating: 4.5,
        category: "Biography",
        author: "Walter Isaacson",
        publicationDate: "2011-10-24",
        numPage: 656
    });

    // mongoose-fixture expects implementor to return
    // the callback passed in context
    return callback(error, fixture);
};
